
services:
  db:
    image: postgres
    container_name: user-ms-db
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_LOGIN}
      POSTGRES_PASSWORD: ${DATABASE_SECRET}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - action: rebuild
          path: .
          target: .
    container_name: user-ms
    depends_on:
      - db
    environment:
      - POSTGRES_USER=${DATABASE_LOGIN}
      - POSTGRES_PASSWORD=${DATABASE_SECRET}
      - SPRING_DATASOURCE_URL=${DATABASE_URL}
      - SPRING_DATASOURCE_USERNAME=${DATABASE_LOGIN}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_SECRET}

    ports:
      - "8080:8080"

volumes:
  postgres_data:
