spring:
  datasource:
    url: jdbc:tc:postgresql:9.6.8:///test_database
    username: member
    password: password
  jpa:
    hibernate:
      ddl-auto: create

  flyway:
    enabled: false
  data:
    jdbc:
      dialect: postgresql

quemistry:
  user:
    cipher:
      key: test-encryption-key
      size: 1
