spring:
  application:
    name: user_ms


  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_LOGIN}
    password: ${DATABASE_SECRET}

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    url: ${DATABASE_URL}
    schemas: ${DATABASE_LOGIN}
    user: ${DATABASE_LOGIN}
    password: ${DATABASE_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /v1
      path-mapping:
        health: /user/actuator
  endpoint:
    health:
      show-details: never
      enabled: true

quemistry:
  user:
    cipher:
      key: ${DATABASE_CIPHER_KEY}
      size: ${DATABASE_CIPHER_KEY_SIZE}

server:
  port: 80
