spring:
  application:
    name: user_ms
  profiles:
    active: ${ENV:prod}


  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_LOGIN}
    password: ${DATABASE_SECRET}

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: ${FLYWAY_LOCATION}
    url: ${DATABASE_URL}
    schemas: ${DATABASE_LOGIN}
    user: ${DATABASE_LOGIN}
    password: ${DATABASE_SECRET}
  mail:
    host: smtp.gmail.com
    port: 587
    password: ${SMTP_PASSWORD}
    username: ${SMTP_USER_NAME}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /v1
      path-mapping:
        health: /user/actuator
  endpoint:
    health:
      show-details: never
      enabled: true
  health:
    mail:
      enabled: false
quemistry:
  user:
    front-end:
      url: ${HOST_NAME}
    cipher:
      key: ${DATABASE_CIPHER_KEY}
      iv: ${DATABASE_CIPHER_IV}

server:
  port: 80
