spring:
  mail:
    host: mail.smtp.com
    port: 99
    password: pass
    username: user
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  datasource:
    url: jdbc:tc:postgresql:9.6.8:///test_database
    username: qms_user
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: false
  data:
    jdbc:
      dialect: postgresql

quemistry:
  user:
    front-end:
      url: hostname
    cipher:
      key: test-encryption-key
      iv: iv-key
